# Generated by Django 5.2.7 on 2025-11-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='My playlist'),
            preserve_default=False,
        ),
    ]
